# Generated by Django 3.0.2 on 2020-05-26 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0002_post_year_in_school'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='Почта',
            new_name='Электронная_почта',
        ),
        migrations.RemoveField(
            model_name='post',
            name='year_in_school',
        ),
        migrations.AddField(
            model_name='post',
            name='Тема',
            field=models.CharField(choices=[('MS', '- Выберите тему -'), ('DPO', 'Дополнительно образование'), ('LCT', 'Лекции'), ('CTF', 'Сорвенования CTF'), ('DVLP', 'Разработка ПО'), ('CVL', 'Повышение кваллификации')], default='MS', max_length=4),
        ),
    ]
