# Generated by Django 3.0.2 on 2020-05-26 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0004_auto_20200526_1343'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='Электронная_почта',
            field=models.EmailField(default='default title', max_length=254),
        ),
    ]
